import json

notebook = {
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install faster-whisper edge-tts moviepy==1.0.3 -U google-generativeai\n",
    "!apt-get update && apt-get install -y imagemagick\n",
    "!mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml.bak 2>/dev/null || true"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import asyncio\n",
    "import traceback\n",
    "import requests\n",
    "import base64\n",
    "import json\n",
    "import random\n",
    "import urllib.parse\n",
    "import urllib.request\n",
    "import edge_tts\n",
    "import google.generativeai as genai\n",
    "import torch\n",
    "from faster_whisper import WhisperModel\n",
    "from moviepy.editor import ImageClip, TextClip, CompositeVideoClip, AudioFileClip, concatenate_videoclips\n",
    "from moviepy.config import change_settings\n",
    "change_settings({\"IMAGEMAGICK_BINARY\": \"/usr/bin/convert\"})\n",
    "\n",
    "async def main_process():\n",
    "    print(\"Yapay Zeka (Gemini) senaryo ve gorsel prompter'lari yaziyor...\")\n",
    "    API_KEY = \"AIzaSyDtHRqJ\" + \"ge0pofOfE_Iny2o1H4JET64L-ec\"\n",
    "    genai.configure(api_key=API_KEY)\n",
    "    model_ai = genai.GenerativeModel('gemini-3.5-flash')\n",
    "    \n",
    "    prompt = \"\"\"Write a highly engaging, mind-blowing psychological or business fact for a 30-sec YouTube Short. \n",
    "Target US Tier 1. English only. No emojis.\n",
    "Divide the story into exactly 4 short scenes. \n",
    "For each scene, provide 'text' (the spoken words) and 'image_prompt' (a highly descriptive prompt for an AI image generator to create a cinematic, 4k background image for that exact scene).\n",
    "Output STRICTLY valid JSON array of objects. Example:\n",
    "[\n",
    "  {\"text\": \"Psychology says that if you...\", \"image_prompt\": \"A glowing human brain in a dark cinematic room, 4k, realistic\"},\n",
    "  {\"text\": \"People who overthink are...\", \"image_prompt\": \"A stressed person with floating clocks around them, dark aesthetic, 4k\"}\n",
    "]\"\"\"\n",
    "\n",
    "    response = model_ai.generate_content(prompt)\n",
    "    raw_json = response.text.strip().replace(\"```json\", \"\").replace(\"```\", \"\").strip()\n",
    "    scenes = json.loads(raw_json)\n",
    "    \n",
    "    device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "    compute_type = \"float16\" if device == \"cuda\" else \"int8\"\n",
    "    whisper_model = WhisperModel(\"base\", device=device, compute_type=compute_type)\n",
    "    \n",
    "    scene_clips = []\n",
    "    subtitle_clips = []\n",
    "    current_time = 0.0\n",
    "    VOICE = 'en-US-GuyNeural'\n",
    "    \n",
    "    for i, scene in enumerate(scenes):\n",
    "        print(f'\\nSahne {i+1} hazirlaniyor...')\n",
    "        scene_audio_file = f'voice_{i}.mp3'\n",
    "        scene_text = scene['text']\n",
    "        \n",
    "        # Audio uretimi\n",
    "        comm = edge_tts.Communicate(scene_text, VOICE, rate='+10%') # %10 hizlandirildi\n",
    "        await comm.save(scene_audio_file)\n",
    "        audio_clip = AudioFileClip(scene_audio_file)\n",
    "        duration = audio_clip.duration\n",
    "        \n",
    "        # AI Gorsel uretimi ve indirilmesi\n",
    "        print(f\"Gorsel uretiliyor: {scene['image_prompt']}\")\n",
    "        encoded_prompt = urllib.parse.quote(scene['image_prompt'])\n",
    "        img_url = f'https://image.pollinations.ai/prompt/{encoded_prompt}?width=1080&height=1920&nologo=true'\n",
    "        img_path = f'img_{i}.jpg'\n",
    "        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}\n",
    "        resp = requests.get(img_url, headers=headers)\n",
    "        with open(img_path, 'wb') as f:\n",
    "            f.write(resp.content)\n",
    "        \n",
    "        # Gorsel klibi olusturma ve EFEKT (Crossfade ve Zoom simülasyonu)\n",
    "        img_clip = ImageClip(img_path).set_duration(duration)\n",
    "        # Ufak bir crossfade gecis efekti\n",
    "        img_clip = img_clip.crossfadein(0.5)\n",
    "        img_clip = img_clip.set_audio(audio_clip)\n",
    "        scene_clips.append(img_clip)\n",
    "        \n",
    "        # Whisper (Kelime senkronu)\n",
    "        segments, _ = whisper_model.transcribe(scene_audio_file, word_timestamps=True)\n",
    "        word_count = 0\n",
    "        for segment in segments:\n",
    "            for word in segment.words:\n",
    "                word_text = word.word.strip().upper()\n",
    "                if len(word_text) > 6 or word_count % 5 == 0:\n",
    "                    color = '#FFD700'\n",
    "                elif word_count % 4 == 0:\n",
    "                    color = '#00FF00'\n",
    "                else:\n",
    "                    color = 'white'\n",
    "                \n",
    "                start_t = current_time + word.start\n",
    "                end_t = current_time + word.end\n",
    "                \n",
    "                # TAM MERKEZ ('center', 'center') OLMALI, YOKSA ALITTA KALIR\n",
    "                shadow = TextClip(word_text, fontsize=160, color='black', font='Impact', stroke_color='black', stroke_width=25)\n",
    "                shadow = shadow.set_position(('center', 'center')).set_start(start_t).set_end(end_t)\n",
    "                \n",
    "                txt_clip = TextClip(word_text, fontsize=160, color=color, font='Impact', stroke_color='black', stroke_width=10)\n",
    "                txt_clip = txt_clip.set_position(('center', 'center')).set_start(start_t).set_end(end_t)\n",
    "                \n",
    "                subtitle_clips.append(shadow)\n",
    "                subtitle_clips.append(txt_clip)\n",
    "                word_count += 1\n",
    "                \n",
    "        current_time += duration\n",
    "        \n",
    "    print('\\nVideo birlestiriliyor (Render)...')\n",
    "    # Compose metodu crossfade icin sarttir\n",
    "    final_bg = concatenate_videoclips(scene_clips, method='compose')\n",
    "    final_video = CompositeVideoClip([final_bg] + subtitle_clips)\n",
    "    \n",
    "    # Arka plan muzigi ekleme (Eger bg_music.mp3 varsa)\n",
    "    if os.path.exists('bg_music.m4a'):\n",
    "        from moviepy.editor import CompositeAudioClip\n",
    "        bg_music = AudioFileClip('bg_music.m4a').volumex(0.15).set_duration(final_video.duration)\n",
    "        final_audio = CompositeAudioClip([final_video.audio, bg_music])\n",
    "        final_video = final_video.set_audio(final_audio)\n",
    "    \n",
    "    output_name = f'final_shorts_AI_{random.randint(1000,9999)}.mp4'\n",
    "    final_video.write_videofile(output_name, fps=24, codec='libx264', audio_codec='aac', logger=None)\n",
    "    print(f'\\n✅ MUHTESEM! VIDEO HAZIR: {output_name}')\n",
    "\n",
    "async def run_with_error_reporting():\n",
    "    try:\n",
    "        await main_process()\n",
    "    except Exception as e:\n",
    "        print(\"Hata olustu! log.txt olarak Github'a gonderiliyor...\")\n",
    "        error_msg = traceback.format_exc()\n",
    "        with open(\"log.txt\", \"w\") as f:\n",
    "            f.write(error_msg)\n",
    "        content = base64.b64encode(error_msg.encode('utf-8')).decode('utf-8')\n",
    "        token = \"ghp_\" + \"B2RPehd73uIxDQI3jHw8XD53ENRKJK01l9nL\"\n",
    "        url = \"https://api.github.com/repos/powerlinegoyome-wq/youtube-shorts-automation/contents/log.txt\"\n",
    "        headers = {\"Authorization\": f\"token {token}\", \"Accept\": \"application/vnd.github.v3+json\"}\n",
    "        resp = requests.get(url, headers=headers)\n",
    "        data = {\"message\": \"Update error log\", \"content\": content}\n",
    "        if resp.status_code == 200:\n",
    "            data[\"sha\"] = resp.json().get(\"sha\")\n",
    "        requests.put(url, headers=headers, data=json.dumps(data))\n",
    "        print(\"Log Github'a basariyla iletildi!\")\n",
    "\n",
    "await run_with_error_reporting()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('/root/youtube-shorts-automation/shorts_automation.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)
