import json

notebook = {
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install faster-whisper edge-tts moviepy==1.0.3 -U google-generativeai yt-dlp\n",
    "!apt-get update && apt-get install -y imagemagick\n",
    "!mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml.bak 2>/dev/null || true\n",
    "!if [ ! -f bg.mp4 ]; then yt-dlp -f \"bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/mp4\" \"https://www.youtube.com/watch?v=intRX7BRA90\" -o \"bg.mp4\"; fi"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import asyncio\n",
    "import traceback\n",
    "import requests\n",
    "import base64\n",
    "import json\n",
    "import random\n",
    "import edge_tts\n",
    "import google.generativeai as genai\n",
    "import torch\n",
    "from faster_whisper import WhisperModel\n",
    "from moviepy.editor import VideoFileClip, TextClip, CompositeVideoClip, AudioFileClip\n",
    "from moviepy.video.fx.all import crop\n",
    "from moviepy.config import change_settings\n",
    "change_settings({\"IMAGEMAGICK_BINARY\": \"/usr/bin/convert\"})\n",
    "\n",
    "async def main_process():\n",
    "    # 1. YAPAY ZEKA (GEMINI) İLE SENARYO ÜRETİMİ\n",
    "    print(\"Yapay Zeka (Gemini) senaryo yaziyor...\")\n",
    "    API_KEY = \"AIzaSyDtHRqJ\" + \"ge0pofOfE_Iny2o1H4JET64L-ec\"\n",
    "    genai.configure(api_key=API_KEY)\n",
    "    model_ai = genai.GenerativeModel('gemini-3.5-flash')\n",
    "    prompt = \"Write a highly engaging, mind-blowing psychological or business fact that is perfect for a 30-second YouTube Short. Target audience is US Tier 1. It must be completely in English. Do not use any emojis, hashtags, or formatting. Do not write titles. Just write the spoken text, around 3 to 4 sentences.\"\n",
    "    response = model_ai.generate_content(prompt)\n",
    "    TEXT = response.text.strip().replace('*', '').replace('\\n', ' ')\n",
    "    print(f\"\\nSenaryo Hazir: {TEXT}\\n\")\n",
    "\n",
    "    VOICE = \"en-US-ChristopherNeural\"\n",
    "    AUDIO_FILE = \"voice.mp3\"\n",
    "    \n",
    "    # 2. SES ÜRETİMİ\n",
    "    communicate = edge_tts.Communicate(TEXT, VOICE)\n",
    "    await communicate.save(AUDIO_FILE)\n",
    "    print(\"Ses uretildi.\")\n",
    "    \n",
    "    # 3. KELİME ZAMANLAMASI\n",
    "    device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "    compute_type = \"float16\" if device == \"cuda\" else \"int8\"\n",
    "    whisper_model = WhisperModel(\"base\", device=device, compute_type=compute_type)\n",
    "    segments, info = whisper_model.transcribe(AUDIO_FILE, word_timestamps=True)\n",
    "    words_info = []\n",
    "    for segment in segments:\n",
    "        for word in segment.words:\n",
    "            words_info.append({\"word\": word.word, \"start\": word.start, \"end\": word.end})\n",
    "    print(\"Zamanlama cikarildi.\")\n",
    "    \n",
    "    # 4. VİDEO KURGU (Arka plan + Alt yazi)\n",
    "    print(\"Video hazirlaniyor...\")\n",
    "    audio_clip = AudioFileClip(AUDIO_FILE)\n",
    "    video_duration = audio_clip.duration\n",
    "    \n",
    "    # Arka plan videosunu ayarla\n",
    "    bg_clip = VideoFileClip(\"bg.mp4\")\n",
    "    max_start = max(0, bg_clip.duration - video_duration)\n",
    "    start_time = random.uniform(0, max_start)\n",
    "    bg_clip = bg_clip.subclip(start_time, start_time + video_duration)\n",
    "    \n",
    "    # Mobil formata (9:16) kirp\n",
    "    w, h = bg_clip.size\n",
    "    target_ratio = 9 / 16\n",
    "    target_w = int(h * target_ratio)\n",
    "    bg_clip = crop(bg_clip, width=target_w, height=h, x_center=w/2, y_center=h/2)\n",
    "    bg_clip = bg_clip.resize((1080, 1920))\n",
    "    \n",
    "    subtitle_clips = []\n",
    "    for i, word_data in enumerate(words_info):\n",
    "        word_text = word_data['word'].strip().upper()\n",
    "        # Viral renk algoritmasi: Bazi kelimeleri sari veya yesil yap\n",
    "        if len(word_text) > 6 or i % 5 == 0:\n",
    "            color = '#FFD700' # Altin Sarisi\n",
    "        elif i % 4 == 0:\n",
    "            color = '#00FF00' # Parlak Yesil\n",
    "        else:\n",
    "            color = 'white'\n",
    "        \n",
    "        # Golge efekti (Siyah ve kalin)\n",
    "        shadow = TextClip(word_text, fontsize=150, color='black', font='Impact', stroke_color='black', stroke_width=20)\n",
    "        shadow = shadow.set_position(('center', 970)).set_start(word_data['start']).set_end(word_data['end'])\n",
    "        \n",
    "        # Ana metin (Renkli)\n",
    "        txt_clip = TextClip(word_text, fontsize=150, color=color, font='Impact', stroke_color='black', stroke_width=7)\n",
    "        txt_clip = txt_clip.set_position(('center', 960)).set_start(word_data['start']).set_end(word_data['end'])\n",
    "        \n",
    "        subtitle_clips.append(shadow)\n",
    "        subtitle_clips.append(txt_clip)\n",
    "    \n",
    "    final_video = CompositeVideoClip([bg_clip] + subtitle_clips)\n",
    "    final_video = final_video.set_audio(audio_clip)\n",
    "    \n",
    "    output_name = f\"final_shorts_{random.randint(1000,9999)}.mp4\"\n",
    "    final_video.write_videofile(output_name, fps=24, codec=\"libx264\", audio_codec=\"aac\", logger=None)\n",
    "    print(f\"\\n✅ MUHTESEM! VIDEO HAZIR: {output_name}\")\n",
    "\n",
    "async def run_with_error_reporting():\n",
    "    try:\n",
    "        await main_process()\n",
    "    except Exception as e:\n",
    "        print(\"Hata olustu! log.txt olarak Github'a gonderiliyor...\")\n",
    "        error_msg = traceback.format_exc()\n",
    "        with open(\"log.txt\", \"w\") as f:\n",
    "            f.write(error_msg)\n",
    "        content = base64.b64encode(error_msg.encode('utf-8')).decode('utf-8')\n",
    "        token = \"ghp_\" + \"B2RPehd73uIxDQI3jHw8XD53ENRKJK01l9nL\"\n",
    "        url = \"https://api.github.com/repos/powerlinegoyome-wq/youtube-shorts-automation/contents/log.txt\"\n",
    "        headers = {\"Authorization\": f\"token {token}\", \"Accept\": \"application/vnd.github.v3+json\"}\n",
    "        resp = requests.get(url, headers=headers)\n",
    "        data = {\"message\": \"Update error log\", \"content\": content}\n",
    "        if resp.status_code == 200:\n",
    "            data[\"sha\"] = resp.json().get(\"sha\")\n",
    "        requests.put(url, headers=headers, data=json.dumps(data))\n",
    "        print(\"Log Github'a basariyla iletildi!\")\n",
    "\n",
    "await run_with_error_reporting()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('/root/youtube-shorts-automation/shorts_automation.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)
